package entidades;
// Generated 11/09/2018 09:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Acao generated by hbm2java
 */
public class Acao  implements java.io.Serializable {


     private int id;
     private Programas programas;
     private String descricao;
     private String variavel;
     private Set grupoAcaos = new HashSet(0);

    public Acao() {
    }

	
    public Acao(int id) {
        this.id = id;
    }
    public Acao(int id, Programas programas, String descricao, String variavel, Set grupoAcaos) {
       this.id = id;
       this.programas = programas;
       this.descricao = descricao;
       this.variavel = variavel;
       this.grupoAcaos = grupoAcaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Programas getProgramas() {
        return this.programas;
    }
    
    public void setProgramas(Programas programas) {
        this.programas = programas;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getVariavel() {
        return this.variavel;
    }
    
    public void setVariavel(String variavel) {
        this.variavel = variavel;
    }
    public Set getGrupoAcaos() {
        return this.grupoAcaos;
    }
    
    public void setGrupoAcaos(Set grupoAcaos) {
        this.grupoAcaos = grupoAcaos;
    }




}


