package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1



/**
 * Alteracao generated by hbm2java
 */
public class Alteracao  implements java.io.Serializable {


     private int id;
     private TipoOperacao tipoOperacao;
     private Usuario usuario;

    public Alteracao() {
    }

    public Alteracao(int id, TipoOperacao tipoOperacao, Usuario usuario) {
       this.id = id;
       this.tipoOperacao = tipoOperacao;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public TipoOperacao getTipoOperacao() {
        return this.tipoOperacao;
    }
    
    public void setTipoOperacao(TipoOperacao tipoOperacao) {
        this.tipoOperacao = tipoOperacao;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


