package entidades;
// Generated 11/09/2018 09:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.envers.Audited;
import static org.hibernate.envers.RelationTargetAuditMode.NOT_AUDITED;

/**
 * Endereco generated by hbm2java
 */
@Audited(targetAuditMode = NOT_AUDITED)
public class Endereco  implements java.io.Serializable {


     private int id;
     private Cidade cidade;
     private String rua;
     private String bairro;
     private String complemento;
     private String cep;
     private int numero;
     private Set enderecosPessoas = new HashSet(0);
     private Set fretes = new HashSet(0);
     private Set unidades = new HashSet(0);

    public Endereco() {
    }

	
    public Endereco(int id, Cidade cidade, String rua, String bairro, String cep, int numero) {
        this.id = id;
        this.cidade = cidade;
        this.rua = rua;
        this.bairro = bairro;
        this.cep = cep;
        this.numero = numero;
    }
    public Endereco(int id, Cidade cidade, String rua, String bairro, String complemento, String cep, int numero, Set enderecosPessoas, Set fretes, Set unidades) {
       this.id = id;
       this.cidade = cidade;
       this.rua = rua;
       this.bairro = bairro;
       this.complemento = complemento;
       this.cep = cep;
       this.numero = numero;
       this.enderecosPessoas = enderecosPessoas;
       this.fretes = fretes;
       this.unidades = unidades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public Set getEnderecosPessoas() {
        return this.enderecosPessoas;
    }
    
    public void setEnderecosPessoas(Set enderecosPessoas) {
        this.enderecosPessoas = enderecosPessoas;
    }
    public Set getFretes() {
        return this.fretes;
    }
    
    public void setFretes(Set fretes) {
        this.fretes = fretes;
    }
    public Set getUnidades() {
        return this.unidades;
    }
    
    public void setUnidades(Set unidades) {
        this.unidades = unidades;
    }




}


