package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1



/**
 * Erro generated by hbm2java
 */
public class Erro  implements java.io.Serializable {


     private int id;
     private Usuario usuario;
     private String descricao;

    public Erro() {
    }

    public Erro(int id, Usuario usuario, String descricao) {
       this.id = id;
       this.usuario = usuario;
       this.descricao = descricao;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


