package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.envers.Audited;

/**
 * EstadoFrete generated by hbm2java
 */
@Audited
public class EstadoFrete  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set fretes = new HashSet(0);

    public EstadoFrete() {
    }

	
    public EstadoFrete(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    public EstadoFrete(int id, String descricao, Set fretes) {
       this.id = id;
       this.descricao = descricao;
       this.fretes = fretes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getFretes() {
        return this.fretes;
    }
    
    public void setFretes(Set fretes) {
        this.fretes = fretes;
    }




}


