package entidades;
// Generated 11/09/2018 09:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Estado generated by hbm2java
 */

public class Estado  implements java.io.Serializable {


     private int id;
     private Pais pais;
     private String nome;
     private String sigla;
     private Set cidades = new HashSet(0);

    public Estado() {
    }

	
    public Estado(int id, Pais pais, String nome, String sigla) {
        this.id = id;
        this.pais = pais;
        this.nome = nome;
        this.sigla = sigla;
    }
    public Estado(int id, Pais pais, String nome, String sigla, Set cidades) {
       this.id = id;
       this.pais = pais;
       this.nome = nome;
       this.sigla = sigla;
       this.cidades = cidades;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Pais getPais() {
        return this.pais;
    }
    
    public void setPais(Pais pais) {
        this.pais = pais;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSigla() {
        return this.sigla;
    }
    
    public void setSigla(String sigla) {
        this.sigla = sigla;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }




}


