package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1



/**
 * FreteViagem generated by hbm2java
 */
public class FreteViagem  implements java.io.Serializable {


     private int id;
     private Frete frete;
     private Viagem viagem;

    public FreteViagem() {
    }

    public FreteViagem(int id, Frete frete, Viagem viagem) {
       this.id = id;
       this.frete = frete;
       this.viagem = viagem;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Frete getFrete() {
        return this.frete;
    }
    
    public void setFrete(Frete frete) {
        this.frete = frete;
    }
    public Viagem getViagem() {
        return this.viagem;
    }
    
    public void setViagem(Viagem viagem) {
        this.viagem = viagem;
    }




}


