package entidades;
// Generated 11/09/2018 09:51:52 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.envers.Audited;

/**
 * Grupo generated by hbm2java
 */
@Audited
public class Grupo  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set usuarioGruposes = new HashSet(0);
     private Set grupoAcaos = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    public Grupo(int id, String descricao, Set usuarioGruposes, Set grupoAcaos, Set usuarios) {
       this.id = id;
       this.descricao = descricao;
       this.usuarioGruposes = usuarioGruposes;
       this.grupoAcaos = grupoAcaos;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getUsuarioGruposes() {
        return this.usuarioGruposes;
    }
    
    public void setUsuarioGruposes(Set usuarioGruposes) {
        this.usuarioGruposes = usuarioGruposes;
    }
    public Set getGrupoAcaos() {
        return this.grupoAcaos;
    }
    
    public void setGrupoAcaos(Set grupoAcaos) {
        this.grupoAcaos = grupoAcaos;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


