package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1



/**
 * GrupoProgramas generated by hbm2java
 */
public class GrupoProgramas  implements java.io.Serializable {


     private int id;
     private Grupo grupo;
     private Programas programas;

    public GrupoProgramas() {
    }

    public GrupoProgramas(int id, Grupo grupo, Programas programas) {
       this.id = id;
       this.grupo = grupo;
       this.programas = programas;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Programas getProgramas() {
        return this.programas;
    }
    
    public void setProgramas(Programas programas) {
        this.programas = programas;
    }




}


