package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.envers.Audited;

/**
 * Grupo generated by hbm2java
 */
@Audited
public class Grupo  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set grupoProgramases = new HashSet(0);
     private Set usuarioGruposes = new HashSet(0);

    public Grupo() {
    }

	
    public Grupo(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    public Grupo(int id, String descricao, Set grupoProgramases, Set usuarioGruposes) {
       this.id = id;
       this.descricao = descricao;
       this.grupoProgramases = grupoProgramases;
       this.usuarioGruposes = usuarioGruposes;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getGrupoProgramases() {
        return this.grupoProgramases;
    }
    
    public void setGrupoProgramases(Set grupoProgramases) {
        this.grupoProgramases = grupoProgramases;
    }
    public Set getUsuarioGruposes() {
        return this.usuarioGruposes;
    }
    
    public void setUsuarioGruposes(Set usuarioGruposes) {
        this.usuarioGruposes = usuarioGruposes;
    }




}


