package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import org.hibernate.envers.Audited;

/**
 * Pais generated by hbm2java
 */
@Audited
public class Pais  implements java.io.Serializable {


     private int id;
     private String nome;
     private Set estados = new HashSet(0);

    public Pais() {
    }

	
    public Pais(int id, String nome) {
        this.id = id;
        this.nome = nome;
    }
    public Pais(int id, String nome, Set estados) {
       this.id = id;
       this.nome = nome;
       this.estados = estados;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEstados() {
        return this.estados;
    }
    
    public void setEstados(Set estados) {
        this.estados = estados;
    }




}


