package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private int id;
     private String nome;
     private String email;
     private String telefone;
     private Date nascimento;
     private PessoaJuridica pessoaJuridica;
     private Set fretesForRefDetinatario = new HashSet(0);
     private PessoaFisica pessoaFisica;
     private Set fretesForRefSolicitante = new HashSet(0);
     private Set enderecosPessoas = new HashSet(0);
     private Set usuarios = new HashSet(0);

    public Pessoa() {
    }

	
    public Pessoa(int id, String nome, String email, String telefone) {
        this.id = id;
        this.nome = nome;
        this.email = email;
        this.telefone = telefone;
    }
    public Pessoa(int id, String nome, String email, String telefone, Date nascimento, PessoaJuridica pessoaJuridica, Set fretesForRefDetinatario, PessoaFisica pessoaFisica, Set fretesForRefSolicitante, Set enderecosPessoas, Set usuarios) {
       this.id = id;
       this.nome = nome;
       this.email = email;
       this.telefone = telefone;
       this.nascimento = nascimento;
       this.pessoaJuridica = pessoaJuridica;
       this.fretesForRefDetinatario = fretesForRefDetinatario;
       this.pessoaFisica = pessoaFisica;
       this.fretesForRefSolicitante = fretesForRefSolicitante;
       this.enderecosPessoas = enderecosPessoas;
       this.usuarios = usuarios;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public Date getNascimento() {
        return this.nascimento;
    }
    
    public void setNascimento(Date nascimento) {
        this.nascimento = nascimento;
    }
    public PessoaJuridica getPessoaJuridica() {
        return this.pessoaJuridica;
    }
    
    public void setPessoaJuridica(PessoaJuridica pessoaJuridica) {
        this.pessoaJuridica = pessoaJuridica;
    }
    public Set getFretesForRefDetinatario() {
        return this.fretesForRefDetinatario;
    }
    
    public void setFretesForRefDetinatario(Set fretesForRefDetinatario) {
        this.fretesForRefDetinatario = fretesForRefDetinatario;
    }
    public PessoaFisica getPessoaFisica() {
        return this.pessoaFisica;
    }
    
    public void setPessoaFisica(PessoaFisica pessoaFisica) {
        this.pessoaFisica = pessoaFisica;
    }
    public Set getFretesForRefSolicitante() {
        return this.fretesForRefSolicitante;
    }
    
    public void setFretesForRefSolicitante(Set fretesForRefSolicitante) {
        this.fretesForRefSolicitante = fretesForRefSolicitante;
    }
    public Set getEnderecosPessoas() {
        return this.enderecosPessoas;
    }
    
    public void setEnderecosPessoas(Set enderecosPessoas) {
        this.enderecosPessoas = enderecosPessoas;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }




}


