package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1



/**
 * PessoaFisica generated by hbm2java
 */
public class PessoaFisica  implements java.io.Serializable {


     private int refPessoa;
     private Pessoa pessoa;
     private String cpf;
     private String rg;

    public PessoaFisica() {
    }

    public PessoaFisica(Pessoa pessoa, String cpf, String rg) {
       this.pessoa = pessoa;
       this.cpf = cpf;
       this.rg = rg;
    }
   
    public int getRefPessoa() {
        return this.refPessoa;
    }
    
    public void setRefPessoa(int refPessoa) {
        this.refPessoa = refPessoa;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getRg() {
        return this.rg;
    }
    
    public void setRg(String rg) {
        this.rg = rg;
    }




}


