package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import org.hibernate.envers.Audited;

/**
 * ProdutosFrete generated by hbm2java
 */
@Audited
public class ProdutosFrete  implements java.io.Serializable {


     private int id;
     private Frete frete;
     private String descricao;
     private BigDecimal valor;
     private BigDecimal peso;

    public ProdutosFrete() {
    }

    public ProdutosFrete(int id, Frete frete, String descricao, BigDecimal valor, BigDecimal peso) {
       this.id = id;
       this.frete = frete;
       this.descricao = descricao;
       this.valor = valor;
       this.peso = peso;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Frete getFrete() {
        return this.frete;
    }
    
    public void setFrete(Frete frete) {
        this.frete = frete;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public BigDecimal getValor() {
        return this.valor;
    }
    
    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }
    public BigDecimal getPeso() {
        return this.peso;
    }
    
    public void setPeso(BigDecimal peso) {
        this.peso = peso;
    }




}


