package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TipoOperacao generated by hbm2java
 */
public class TipoOperacao  implements java.io.Serializable {


     private int id;
     private String descricao;
     private Set alteracaos = new HashSet(0);

    public TipoOperacao() {
    }

	
    public TipoOperacao(int id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    public TipoOperacao(int id, String descricao, Set alteracaos) {
       this.id = id;
       this.descricao = descricao;
       this.alteracaos = alteracaos;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getAlteracaos() {
        return this.alteracaos;
    }
    
    public void setAlteracaos(Set alteracaos) {
        this.alteracaos = alteracaos;
    }




}


