package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Unidade generated by hbm2java
 */
public class Unidade  implements java.io.Serializable {


     private int id;
     private Endereco endereco;
     private String descricao;
     private Set fretes = new HashSet(0);
     private Set viagemsForRefUnidadeDestino = new HashSet(0);
     private Set viagemsForRefUnidadeOrigem = new HashSet(0);

    public Unidade() {
    }

	
    public Unidade(int id, Endereco endereco, String descricao) {
        this.id = id;
        this.endereco = endereco;
        this.descricao = descricao;
    }
    public Unidade(int id, Endereco endereco, String descricao, Set fretes, Set viagemsForRefUnidadeDestino, Set viagemsForRefUnidadeOrigem) {
       this.id = id;
       this.endereco = endereco;
       this.descricao = descricao;
       this.fretes = fretes;
       this.viagemsForRefUnidadeDestino = viagemsForRefUnidadeDestino;
       this.viagemsForRefUnidadeOrigem = viagemsForRefUnidadeOrigem;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getFretes() {
        return this.fretes;
    }
    
    public void setFretes(Set fretes) {
        this.fretes = fretes;
    }
    public Set getViagemsForRefUnidadeDestino() {
        return this.viagemsForRefUnidadeDestino;
    }
    
    public void setViagemsForRefUnidadeDestino(Set viagemsForRefUnidadeDestino) {
        this.viagemsForRefUnidadeDestino = viagemsForRefUnidadeDestino;
    }
    public Set getViagemsForRefUnidadeOrigem() {
        return this.viagemsForRefUnidadeOrigem;
    }
    
    public void setViagemsForRefUnidadeOrigem(Set viagemsForRefUnidadeOrigem) {
        this.viagemsForRefUnidadeOrigem = viagemsForRefUnidadeOrigem;
    }

}


