package entidades;
// Generated 11/09/2018 09:51:52 by Hibernate Tools 4.3.1

import org.hibernate.envers.Audited;




/**
 * UsuarioGrupos generated by hbm2java
 */
@Audited
public class UsuarioGrupos  implements java.io.Serializable {


     private int id;
     private Grupo grupo;
     private Usuario usuario;

    public UsuarioGrupos() {
    }

    public UsuarioGrupos(int id, Grupo grupo, Usuario usuario) {
       this.id = id;
       this.grupo = grupo;
       this.usuario = usuario;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Grupo getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(Grupo grupo) {
        this.grupo = grupo;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


