package entidades;
// Generated 07/08/2018 15:26:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.envers.Audited;

/**
 * Viagem generated by hbm2java
 */
@Audited
public class Viagem  implements java.io.Serializable {


     private int id;
     private Unidade unidadeByRefUnidadeDestino;
     private Unidade unidadeByRefUnidadeOrigem;
     private Usuario usuario;
     private Veiculo veiculo;
     private Date dataInicio;
     private Date dataFinal;
     private BigDecimal quilometragem;
     private Set freteViagems = new HashSet(0);

    public Viagem() {
    }

	
    public Viagem(int id, Unidade unidadeByRefUnidadeDestino, Unidade unidadeByRefUnidadeOrigem, Usuario usuario, Veiculo veiculo, Date dataInicio, BigDecimal quilometragem) {
        this.id = id;
        this.unidadeByRefUnidadeDestino = unidadeByRefUnidadeDestino;
        this.unidadeByRefUnidadeOrigem = unidadeByRefUnidadeOrigem;
        this.usuario = usuario;
        this.veiculo = veiculo;
        this.dataInicio = dataInicio;
        this.quilometragem = quilometragem;
    }
    public Viagem(int id, Unidade unidadeByRefUnidadeDestino, Unidade unidadeByRefUnidadeOrigem, Usuario usuario, Veiculo veiculo, Date dataInicio, Date dataFinal, BigDecimal quilometragem, Set freteViagems) {
       this.id = id;
       this.unidadeByRefUnidadeDestino = unidadeByRefUnidadeDestino;
       this.unidadeByRefUnidadeOrigem = unidadeByRefUnidadeOrigem;
       this.usuario = usuario;
       this.veiculo = veiculo;
       this.dataInicio = dataInicio;
       this.dataFinal = dataFinal;
       this.quilometragem = quilometragem;
       this.freteViagems = freteViagems;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Unidade getUnidadeByRefUnidadeDestino() {
        return this.unidadeByRefUnidadeDestino;
    }
    
    public void setUnidadeByRefUnidadeDestino(Unidade unidadeByRefUnidadeDestino) {
        this.unidadeByRefUnidadeDestino = unidadeByRefUnidadeDestino;
    }
    public Unidade getUnidadeByRefUnidadeOrigem() {
        return this.unidadeByRefUnidadeOrigem;
    }
    
    public void setUnidadeByRefUnidadeOrigem(Unidade unidadeByRefUnidadeOrigem) {
        this.unidadeByRefUnidadeOrigem = unidadeByRefUnidadeOrigem;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Veiculo getVeiculo() {
        return this.veiculo;
    }
    
    public void setVeiculo(Veiculo veiculo) {
        this.veiculo = veiculo;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataFinal() {
        return this.dataFinal;
    }
    
    public void setDataFinal(Date dataFinal) {
        this.dataFinal = dataFinal;
    }
    public BigDecimal getQuilometragem() {
        return this.quilometragem;
    }
    
    public void setQuilometragem(BigDecimal quilometragem) {
        this.quilometragem = quilometragem;
    }
    public Set getFreteViagems() {
        return this.freteViagems;
    }
    
    public void setFreteViagems(Set freteViagems) {
        this.freteViagems = freteViagems;
    }




}


