/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.awt.Dimension;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.zip.ZipEntry;
import java.util.zip.ZipOutputStream;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import util.Backup;
import util.Formatacao;
import util.Zip;

/**
 *
 * @author ramon
 */
public class IfrBackup extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrBackup
     */
    public IfrBackup() {
        initComponents();
    }

    public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        rbtDados = new javax.swing.JRadioButton();
        rbtCompleto = new javax.swing.JRadioButton();
        btnGerar = new javax.swing.JButton();
        btnRestaurar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();

        setTitle("Backup");

        buttonGroup1.add(rbtDados);
        rbtDados.setSelected(true);
        rbtDados.setText("Apenas Base de Dados");

        buttonGroup1.add(rbtCompleto);
        rbtCompleto.setText("Completo");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnRestaurar.setText("Restaurar");
        btnRestaurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestaurarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtDados)
                    .addComponent(rbtCompleto))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(btnRestaurar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtDados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtCompleto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGerar)
                    .addComponent(btnRestaurar))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Realizar", jPanel1);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(btnFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void btnRestaurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestaurarActionPerformed

        //Zip.extrairZip(new File("C:\\Google Drive\\Univates\\2018 B\\Projeto integredor I\\zipado.zip"), new File("."));
        try {
            JFileChooser fileChooser = new JFileChooser();
            if (rbtDados.isSelected()) {
                fileChooser.setFileFilter(new FileNameExtensionFilter("BackUp", "backup"));
            } else {
                fileChooser.setFileFilter(new FileNameExtensionFilter("ZIP", "zip"));
            }
            int result = fileChooser.showOpenDialog(this);
            File file = null;
            if (result == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
            }

            if (file != null) {
                boolean sucesso = false;
                if (rbtDados.isSelected()) {
                    sucesso = Backup.restoreBD(file.getAbsolutePath());
                } else {
                    
                }
                if (sucesso) {
                    JOptionPane.showMessageDialog(this, "Backup efetuado com Sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao restaurar Backup!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Operação cancelada pelo usuário!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao restaurar Backup!");
            Logger.getLogger(IfrBackup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRestaurarActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        try {
            JFileChooser fileChooser = new JFileChooser();
            fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
            fileChooser.setApproveButtonText("Selecionar");
            int result = fileChooser.showOpenDialog(this);
            File file = null;
            if (result == JFileChooser.APPROVE_OPTION) {
                file = fileChooser.getSelectedFile();
            }

            if (file != null) {
                boolean sucesso = false;
                String dataHora = Formatacao.getDataHoraAtualArquivo();
                if (rbtDados.isSelected()) {
                    sucesso = Backup.backupBD(file.getAbsolutePath() + "\\TranSOFT " + dataHora + ".backup");
                } else {
                    if (file.getAbsolutePath().equals(new File("").getAbsolutePath())) {
                        JOptionPane.showMessageDialog(this, "Destino do Backup não pode ser na pasta de instalação!");
                    } else {
                        sucesso = Backup.backupBD("TranSOFT.backup");
                        if (sucesso) {
                            Zip.zipFolder(".", file.getAbsolutePath() + "\\TranSOFT " + dataHora + ".zip");
                        }
                    }
                }
                if (sucesso) {
                    JOptionPane.showMessageDialog(this, "Backup efetuado com Sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao efetuar Backup!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Operação cancelada pelo usuário!");
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao efetuar Backup!");
            Logger.getLogger(IfrBackup.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerar;
    private javax.swing.JButton btnRestaurar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton rbtCompleto;
    private javax.swing.JRadioButton rbtDados;
    // End of variables declaration//GEN-END:variables
}
