/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import daos.Dao;
import daos.PessoaFisicaDao;
import daos.PessoaJuridicaDao;
import entidades.ComboItens;
import entidades.Pessoa;
import entidades.PessoaFisica;
import entidades.PessoaJuridica;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;
import util.FormataCampo;
import util.Formatacao;
import util.HibernateUtil;
import util.Validacao;

/**
 *
 * @author ramon
 */
public class IfrPessoa extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrPessoa
     */
    private Pessoa atual = new Pessoa();
    private PessoaFisica pfAtual = new PessoaFisica();
    private PessoaJuridica pjAtual = new PessoaJuridica();

    public IfrPessoa() {
        initComponents();
        pfAtual.setPessoa(atual);
        pjAtual.setPessoa(atual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        radJuridica = new javax.swing.JRadioButton();
        radFisica = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        lblPrimeiroNome = new javax.swing.JLabel();
        tfdPrimeiroNome = new javax.swing.JTextField();
        lblRG = new javax.swing.JLabel();
        tfdSegundo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        ftfCodigo = new javax.swing.JFormattedTextField();
        lblData = new javax.swing.JLabel();
        ftfData = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        ftfTelefone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        tfdEmail = new javax.swing.JTextField();
        lblAvisoPrimeiroNome = new javax.swing.JLabel();
        lblAvisoSegundo = new javax.swing.JLabel();
        lblAvisoCodigo = new javax.swing.JLabel();
        lblAvisoData = new javax.swing.JLabel();
        btnGravarPessoa = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblAvisoEmail = new javax.swing.JLabel();
        lblAvisoTelefone = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        tfdLogradouro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfdNumero = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        ftfCep = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cbPais = new javax.swing.JComboBox<>();
        cbEstado = new javax.swing.JComboBox<>();
        cbCidade = new javax.swing.JComboBox<>();
        tfdBairro = new javax.swing.JTextField();
        lblAvisoLogradouro = new javax.swing.JLabel();
        lblAvisoCep = new javax.swing.JLabel();
        btnGravarEndereco = new javax.swing.JButton();
        lblAvisoBairro = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JButton();
        tfdComplemento = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        tfdConsulta = new javax.swing.JTextField();
        cbFiltro = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPessoa = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        radPfisicaC = new javax.swing.JRadioButton();
        radPjuridicaC = new javax.swing.JRadioButton();
        btnFechar = new javax.swing.JButton();

        setTitle("Cadastro de Pessoas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane4.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane4StateChanged(evt);
            }
        });

        buttonGroup1.add(radJuridica);
        radJuridica.setText("Pessoa Jurídica");
        radJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radJuridicaActionPerformed(evt);
            }
        });

        buttonGroup1.add(radFisica);
        radFisica.setText("Pessoa Física");
        radFisica.setSelected(true);
        radFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radFisicaActionPerformed(evt);
            }
        });

        jLabel1.setText("Tipo *");

        lblPrimeiroNome.setText("Nome completo *");

        tfdPrimeiroNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdPrimeiroNomeFocusLost(evt);
            }
        });
        tfdPrimeiroNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdPrimeiroNomeKeyTyped(evt);
            }
        });

        lblRG.setText("RG *");

        tfdSegundo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdSegundoFocusLost(evt);
            }
        });
        tfdSegundo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdSegundoKeyTyped(evt);
            }
        });

        lblCodigo.setText("CPF *");

        try {
            ftfCodigo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCodigo.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftfCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfCodigoFocusLost(evt);
            }
        });

        lblData.setText("Nascimento");

        try {
            ftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfData.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        ftfData.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfDataFocusLost(evt);
            }
        });

        jLabel6.setText("Telefone");

        try {
            ftfTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        ftfTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfTelefoneFocusLost(evt);
            }
        });

        jLabel7.setText("Email");

        tfdEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdEmailFocusLost(evt);
            }
        });
        tfdEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdEmailKeyTyped(evt);
            }
        });

        lblAvisoPrimeiroNome.setText("Nome Inválido!");
        lblAvisoPrimeiroNome.setVisible(false);

        lblAvisoSegundo.setText("RG Inválido!");
        lblAvisoSegundo.setVisible(false);

        lblAvisoCodigo.setText("CPF Inválido!");
        lblAvisoCodigo.setVisible(false);

        lblAvisoData.setText("Data Inválida!");
        lblAvisoData.setVisible(false);

        btnGravarPessoa.setText("Gravar");
        btnGravarPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarPessoaActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblAvisoEmail.setText("Email Inválido!");
        lblAvisoEmail.setVisible(false);

        lblAvisoTelefone.setText("Telefone Inválido!");
        lblAvisoTelefone.setVisible(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRG)
                                    .addComponent(lblCodigo)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel7)
                                    .addComponent(lblPrimeiroNome)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblData))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvisoData))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ftfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAvisoCodigo)
                                    .addComponent(lblAvisoSegundo)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvisoEmail))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvisoTelefone))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfdPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(radFisica)
                                        .addGap(0, 0, 0)
                                        .addComponent(radJuridica)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblAvisoPrimeiroNome)))
                        .addGap(0, 232, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGravarPessoa)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(radFisica)
                        .addComponent(radJuridica)))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrimeiroNome)
                    .addComponent(tfdPrimeiroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoPrimeiroNome))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRG)
                    .addComponent(tfdSegundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoSegundo))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblCodigo))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvisoCodigo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblData)
                    .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfdEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ftfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoTelefone))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarPessoa)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        jTabbedPane4.addTab("Dados Pessoais", jPanel2);

        jLabel8.setText("Logradouro *");

        tfdLogradouro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdLogradouroFocusLost(evt);
            }
        });
        tfdLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdLogradouroKeyTyped(evt);
            }
        });

        jLabel9.setText("nº");

        tfdNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfdNumeroKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdNumeroKeyTyped(evt);
            }
        });

        jLabel10.setText("CEP *");

        try {
            ftfCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfCep.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ftfCepFocusLost(evt);
            }
        });

        jLabel11.setText("Complemento");

        jLabel12.setText("País *");

        jLabel13.setText("Estado *");

        jLabel14.setText("Cidade *");

        jLabel15.setText("Bairro *");

        cbPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaisActionPerformed(evt);
            }
        });

        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });

        tfdBairro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfdBairroFocusLost(evt);
            }
        });
        tfdBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfdBairroKeyTyped(evt);
            }
        });

        lblAvisoLogradouro.setText("Logradouro Inválido");
        lblAvisoLogradouro.setVisible(false);

        lblAvisoCep.setText("CEP Inválido");
        lblAvisoCep.setVisible(false);

        btnGravarEndereco.setText("Gravar");
        btnGravarEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarEnderecoActionPerformed(evt);
            }
        });

        lblAvisoBairro.setText("Bairro Inválido!");
        lblAvisoBairro.setVisible(false);

        btnCancelar2.setText("Cancelar");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfdBairro)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblAvisoCep))
                            .addComponent(tfdLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAvisoLogradouro)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(lblAvisoBairro))
                        .addGap(284, 284, 284))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnCancelar2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGravarEndereco))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfdComplemento)
                                    .addComponent(cbCidade, 0, 145, Short.MAX_VALUE))))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfdLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(tfdNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAvisoLogradouro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(ftfCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAvisoCep))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(tfdComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(cbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfdBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(lblAvisoBairro))))
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravarEndereco)
                    .addComponent(btnCancelar2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Endereço", jPanel3);

        jLabel16.setText("Critério");

        cbFiltro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CPF", "Nome", "RG" }));
        cbFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFiltroActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblPessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Nome Completo", "CPF", "Nascimento"
            }
        ));
        jScrollPane2.setViewportView(tblPessoa);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo");

        buttonGroup3.add(radPfisicaC);
        radPfisicaC.setText("Pessoa Física");
        radPfisicaC.setSelected(true);
        radPfisicaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPfisicaCActionPerformed(evt);
            }
        });

        buttonGroup3.add(radPjuridicaC);
        radPjuridicaC.setText("Pessoa Jurídica");
        radPjuridicaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radPjuridicaCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfdConsulta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar)))))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(radPfisicaC)
                .addGap(18, 18, 18)
                .addComponent(radPjuridicaC)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(radPfisicaC)
                    .addComponent(radPjuridicaC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfdConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(cbFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addGap(3, 3, 3))
        );

        jTabbedPane4.addTab("Consulta", jPanel4);

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(620, 620, 620)
                        .addComponent(btnFechar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarEnderecoActionPerformed

    }//GEN-LAST:event_btnGravarEnderecoActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed

    }//GEN-LAST:event_cbEstadoActionPerformed

    private void cbPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaisActionPerformed

    }//GEN-LAST:event_cbPaisActionPerformed

    private void radJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radJuridicaActionPerformed
        this.paraJuridica();
    }//GEN-LAST:event_radJuridicaActionPerformed

    private void radFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radFisicaActionPerformed
        this.paraFisica();
    }//GEN-LAST:event_radFisicaActionPerformed

    private void tfdPrimeiroNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdPrimeiroNomeKeyTyped
        if (radFisica.isSelected()) {
            FormataCampo.semNumeros(evt);
        }
        FormataCampo.limitaTamanho(tfdPrimeiroNome.getText(), evt, 250);
    }//GEN-LAST:event_tfdPrimeiroNomeKeyTyped

    private void tfdSegundoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdSegundoKeyTyped
        if (radFisica.isSelected()) {
            FormataCampo.somenteNumeros(evt);
            FormataCampo.limitaTamanho(tfdSegundo.getText(), evt, 10);
        } else {
            FormataCampo.limitaTamanho(tfdSegundo.getText(), evt, 100);
        }
    }//GEN-LAST:event_tfdSegundoKeyTyped

    private void tfdEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdEmailKeyTyped
        FormataCampo.limitaTamanho(tfdEmail.getText(), evt, 250);
    }//GEN-LAST:event_tfdEmailKeyTyped

    private void tfdLogradouroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdLogradouroKeyTyped
        FormataCampo.limitaTamanho(tfdLogradouro.getText(), evt, 80);
    }//GEN-LAST:event_tfdLogradouroKeyTyped

    private void tfdNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdNumeroKeyTyped
        FormataCampo.somenteNumeros(evt);
    }//GEN-LAST:event_tfdNumeroKeyTyped

    private void tfdBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdBairroKeyTyped
        FormataCampo.limitaTamanho(tfdBairro.getText(), evt, 100);
    }//GEN-LAST:event_tfdBairroKeyTyped

    private void tfdPrimeiroNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdPrimeiroNomeFocusLost
        if (Formatacao.removerFormatacao(tfdPrimeiroNome.getText()).length() > 0) {
            lblAvisoPrimeiroNome.setVisible(false);
        } else {
            lblAvisoPrimeiroNome.setVisible(true);
        }
        Formatacao.formataJTextField(tfdPrimeiroNome);
    }//GEN-LAST:event_tfdPrimeiroNomeFocusLost

    private void tfdSegundoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdSegundoFocusLost
        if (radFisica.isSelected()) {
            if (tfdSegundo.getText().length() != 10) {
                lblAvisoSegundo.setVisible(true);
            } else {
                lblAvisoSegundo.setVisible(false);
            }
        } else if (Formatacao.removerFormatacao(tfdSegundo.getText()).length() == 0) {
            lblAvisoSegundo.setVisible(true);
        } else {
            lblAvisoSegundo.setVisible(false);
        }
        Formatacao.formataJTextField(tfdSegundo);
    }//GEN-LAST:event_tfdSegundoFocusLost

    private void ftfCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfCodigoFocusLost
        String codigo = Formatacao.removerFormatacao(ftfCodigo.getText());
        boolean valido = true;
        if (radFisica.isSelected()) {
            if (!Validacao.validarCPF(codigo)) {
                valido = false;
            }
        } else if (!Validacao.validarCNPJ(codigo)) {
            valido = false;
        }
        lblAvisoCodigo.setVisible(!valido);
    }//GEN-LAST:event_ftfCodigoFocusLost

    private void ftfDataFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfDataFocusLost
        if (ftfData.getText().equals("  /  /    ")) {
            lblAvisoData.setVisible(false);
        } else if (!ftfData.getText().contains(" ")) {
            if (!Validacao.validarDataFormatada(ftfData.getText())) {
                lblAvisoData.setVisible(true);
            } else {
                lblAvisoData.setVisible(false);
            }
            try {
                Date contrata = Formatacao.transformarParaData(ftfData.getText());
                if (contrata.after(new Date(System.currentTimeMillis()))) {
                    lblAvisoData.setVisible(true);
                } else {
                    lblAvisoData.setVisible(false);
                }
            } catch (Exception e) {
                System.out.println(e);
            }
        } else {
            lblAvisoData.setVisible(true);
        }


    }//GEN-LAST:event_ftfDataFocusLost

    private void tfdLogradouroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdLogradouroFocusLost
        if (Formatacao.removerFormatacao(tfdLogradouro.getText()).length() > 0) {
            lblAvisoLogradouro.setVisible(false);
        } else {
            lblAvisoLogradouro.setVisible(true);
        }
        Formatacao.formataJTextField(tfdLogradouro);
    }//GEN-LAST:event_tfdLogradouroFocusLost

    private void ftfCepFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfCepFocusLost
        if (ftfCep.getText().contains(" ")) {
            lblAvisoCep.setVisible(true);
        } else {
            lblAvisoCep.setVisible(false);
        }
    }//GEN-LAST:event_ftfCepFocusLost

    private void tfdBairroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdBairroFocusLost
        if (Formatacao.removerFormatacao(tfdBairro.getText()).length() > 0) {
            lblAvisoBairro.setVisible(false);
        } else {
            lblAvisoBairro.setVisible(true);
        }
        Formatacao.formataJTextField(tfdBairro);
    }//GEN-LAST:event_tfdBairroFocusLost

    private void jTabbedPane4StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane4StateChanged
        if (jTabbedPane4.getSelectedIndex() == 2) {
            cbFiltro.removeAllItems();
            cbFiltro.addItem("CPF");
            cbFiltro.addItem("Nome");
            cbFiltro.addItem("RG");
            radPfisicaC.setSelected(true);
        }
    }//GEN-LAST:event_jTabbedPane4StateChanged

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (radPfisicaC.isSelected()) {
            PessoaFisicaDao.popularTabelaFiltro(tblPessoa, tfdConsulta.getText(), cbFiltro.getSelectedItem().toString());
        } else {
            PessoaJuridicaDao.popularTabelaFiltro(tblPessoa, tfdConsulta.getText(), cbFiltro.getSelectedItem().toString());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        try {
            this.resetaCampos();
            ftfCodigo.setEditable(false);
            radFisica.setEnabled(false);
            radJuridica.setEnabled(false);
            int idPessoa = Integer.parseInt(String.valueOf(tblPessoa.getValueAt(tblPessoa.getSelectedRow(), 0)));
            PessoaFisica pf = new PessoaFisica();;
            PessoaJuridica pj = new PessoaJuridica();;
            Pessoa p;

            if (radPfisicaC.isSelected()) {
                pf = PessoaFisicaDao.buscaId(idPessoa);
                p = pf.getPessoa();
                pfAtual = pf;
                radFisica.setSelected(true);
                this.paraFisica();
            } else {
                pj = PessoaJuridicaDao.buscaId(idPessoa);
                p = pj.getPessoa();
                pjAtual = pj;
                radJuridica.setSelected(true);
                this.paraJuridica();
            }

            atual = p;

            tfdPrimeiroNome.setText(p.getNome());
            if (radFisica.isSelected()) {
                tfdSegundo.setText(pf.getRg());
                ftfCodigo.setText(pf.getCpf());
            } else {
                tfdSegundo.setText(pj.getNomeFantasia());
                ftfCodigo.setText(pj.getCnpj());
            }
            if (p.getNascimento() != null) {
                ftfData.setText(Formatacao.ajustaDataDMA(p.getNascimento().toString()));
            }

            tfdEmail.setText(p.getEmail());
            ftfTelefone.setText(p.getTelefone());

            jTabbedPane4.setSelectedIndex(0);
        } catch (Exception e) {
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Escolha a pessoa a ser EDITADA!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnGravarPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarPessoaActionPerformed
        String erro = validaCamposDadosPessoais();
        if (!erro.equals("")) {
            jTabbedPane4.setSelectedIndex(0);
            JOptionPane.showMessageDialog(this, "Complete o(s) seguinte(s) dado(s): \n" + erro);
        } else {
            atual.setEmail(tfdEmail.getText());
            if (!ftfData.getText().equalsIgnoreCase("  /  /    ")) {
                try {
                    atual.setNascimento(Formatacao.transformarParaData(ftfData.getText()));
                } catch (ParseException ex) {
                    Logger.getLogger(IfrPessoa.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                 atual.setNascimento(null);
            }
            atual.setNome(tfdPrimeiroNome.getText());
            atual.setTelefone(ftfTelefone.getText());

            Object salvar;
            if (radFisica.isSelected()) {
                pfAtual.setCpf(ftfCodigo.getText());
                pfAtual.setRg(tfdSegundo.getText());
                salvar = pfAtual;
            } else {
                pjAtual.setCnpj(ftfCodigo.getText());
                pjAtual.setNomeFantasia(tfdSegundo.getText());
                salvar = pjAtual;
            }

            String mensagemAtualizar = "Sucesso";
            if (atual.getId() != 0) {
                mensagemAtualizar = Dao.salvar(atual);
            }

            if (Dao.salvar(salvar).equals("Sucesso") && mensagemAtualizar.equals("Sucesso")) {
                ftfCodigo.setEditable(false);
                JOptionPane.showMessageDialog(this, "Pessoa cadastrada com sucesso!");
                radFisica.setEnabled(false);
                radJuridica.setEnabled(false);
                jTabbedPane4.setSelectedIndex(1);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao cadastrar pessoa!");
            }
            jTabbedPane4.setSelectedIndex(1);
        }
    }//GEN-LAST:event_btnGravarPessoaActionPerformed

    private void radPjuridicaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPjuridicaCActionPerformed
        cbFiltro.removeAllItems();
        cbFiltro.addItem("CNPJ");
        cbFiltro.addItem("Razão Social");
        cbFiltro.addItem("Nome Fantasia");
    }//GEN-LAST:event_radPjuridicaCActionPerformed

    private void radPfisicaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radPfisicaCActionPerformed
        cbFiltro.removeAllItems();
        cbFiltro.addItem("CPF");
        cbFiltro.addItem("Nome");
        cbFiltro.addItem("RG");
    }//GEN-LAST:event_radPfisicaCActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnFecharActionPerformed

    private void tfdNumeroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfdNumeroKeyPressed
        FormataCampo.bloquearColar(evt);
    }//GEN-LAST:event_tfdNumeroKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.resetaCampos();
        atual = new Pessoa();
        pfAtual = new PessoaFisica();
        pjAtual = new PessoaJuridica();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
        this.resetaCampos();
        jTabbedPane4.setSelectedIndex(0);
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    private void tfdEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfdEmailFocusLost
        String email = tfdEmail.getText();
        if (email.length() > 0) {
            if (Validacao.validarEmail(email)) {
                lblAvisoEmail.setVisible(false);
            } else {
                lblAvisoEmail.setVisible(true);
            }
        } else {
            lblAvisoEmail.setVisible(false);
        }
    }//GEN-LAST:event_tfdEmailFocusLost

    private void ftfTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ftfTelefoneFocusLost
        String telefone = ftfTelefone.getText().trim();
        if (!telefone.equals("(  )")) {
            if (telefone.length() < 13) {
                lblAvisoTelefone.setVisible(true);
            } else {
                lblAvisoTelefone.setVisible(false);
            }
        } else {
            lblAvisoTelefone.setVisible(false);
        }
    }//GEN-LAST:event_ftfTelefoneFocusLost

    private void cbFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFiltroActionPerformed
    private String validaCamposDadosPessoais() {
        String erro = "";
        if (Formatacao.removerFormatacao(tfdPrimeiroNome.getText()).length() == 0) {
            lblAvisoPrimeiroNome.setVisible(true);
            if (radFisica.isSelected()) {
                erro = "Insira o Nome. \n";
            } else {
                erro = "Insira a Razão Social. \n";
            }
        }

        if (radFisica.isSelected()) {
            if (tfdSegundo.getText().length() != 10) {
                erro = erro + "Insira o RG. \n";
                lblAvisoSegundo.setVisible(true);
            }
        } else if (Formatacao.removerFormatacao(tfdSegundo.getText()).length() == 0) {
            lblAvisoSegundo.setVisible(true);
            erro = erro + "Insira o Nome Fantasia. \n";
        }

        String codigo = Formatacao.removerFormatacao(ftfCodigo.getText());

        if (radFisica.isSelected()) {
            if (!Validacao.validarCPF(codigo)) {
                lblAvisoCodigo.setVisible(true);
                erro = erro + "CPF Inválido. \n";
            }
        } else if (!Validacao.validarCNPJ(codigo)) {
            lblAvisoCodigo.setVisible(true);
            erro = erro + "CNPJ Inválido. \n";
        }

        if (atual.getId() == 0) {
            if (radFisica.isSelected()) {
                if (PessoaFisicaDao.cpfUsado(ftfCodigo.getText())) {
                    lblAvisoCodigo.setVisible(true);
                    erro = erro + "CPF em uso. \n";
                }
            } else if (PessoaJuridicaDao.cnpjUsado(ftfCodigo.getText())) {
                lblAvisoCodigo.setVisible(true);
                erro = erro + "CNPJ em uso. \n";
            }
        }

        if (!ftfData.getText().equals("  /  /    ")) {
            if (!ftfData.getText().contains(" ")) {
                if (!Validacao.validarDataFormatada(ftfData.getText())) {
                    lblAvisoData.setVisible(true);
                    erro = erro + "Data Inválida. \n";
                }
                try {
                    Date data = Formatacao.transformarParaData(ftfData.getText());
                    if (data.after(new Date(System.currentTimeMillis()))) {
                        lblAvisoData.setVisible(true);
                        erro = erro + "Data posterior a hoje. \n";
                    }
                } catch (Exception e) {
                    System.out.println(e);
                }
            } else {
                lblAvisoData.setVisible(true);
                erro = erro + "Data Inválida. \n";
            }
        }

        String email = tfdEmail.getText();
        if (email.length() > 0) {
            if (!Validacao.validarEmail(email)) {
                lblAvisoEmail.setVisible(true);
                erro = erro + "Email Inválido. \n";
            }
        }

        String telefone = ftfTelefone.getText().trim();
        if (!telefone.equals("(  )")) {
            if (telefone.length() < 13) {
                lblAvisoTelefone.setVisible(true);
                erro = erro + "Telefone Inválido. \n";
            }
        }

        return erro;
    }

    private String validaCamposEndereco() {
        String erro = "";
        if (Formatacao.removerFormatacao(tfdLogradouro.getText()).length() == 0) {
            lblAvisoLogradouro.setVisible(true);
            erro = erro + "Insira o Logradouro. \n";
        }
        if (ftfCep.getText().contains(" ")) {
            lblAvisoCep.setVisible(true);
            erro = erro + "CEP inválido. \n";
        }
        if (Formatacao.removerFormatacao(tfdBairro.getText()).length() == 0) {
            lblAvisoBairro.setVisible(true);
            erro = erro + "Insira o Bairro.\n";
        }
        return erro;
    }

    private void resetaCampos() {
        ftfCep.setText("");
        ftfCodigo.setText("");
        ftfData.setText("");
        ftfTelefone.setText("");
        tfdBairro.setText("");
        tfdEmail.setText("");
        tfdLogradouro.setText("");
        tfdNumero.setText("");
        tfdPrimeiroNome.setText("");
        tfdSegundo.setText("");
        this.removeAvisos();
        tfdPrimeiroNome.requestFocus();
        ftfCodigo.setEditable(true);
        radFisica.setEnabled(true);
        radJuridica.setEnabled(true);
    }

    private void paraJuridica() {
        this.removeAvisos();
        tfdPrimeiroNome.requestFocus();
        Formatacao.reformatarCnpj(ftfCodigo);
        lblCodigo.setText("CNPJ *");
        lblData.setText("Fundação");
        lblPrimeiroNome.setText("Razão Social *");
        lblRG.setText("Nome Fantasia *");
        lblAvisoPrimeiroNome.setText("Razão Social Inválida");
        lblAvisoSegundo.setText("Nome Fantasia Inválido");
        lblAvisoCodigo.setText("CNPJ Inválido");
    }

    private void paraFisica() {
        this.removeAvisos();
        tfdPrimeiroNome.requestFocus();
        Formatacao.reformatarCpf(ftfCodigo);
        lblCodigo.setText("CPF *");
        lblData.setText("Nascimento");
        lblPrimeiroNome.setText("Nome completo *");
        lblRG.setText("RG *");
        lblAvisoPrimeiroNome.setText("Nome Inválido");
        lblAvisoSegundo.setText("RG Inválido");
        lblAvisoCodigo.setText("CPF Inválido");
    }

    private void removeAvisos() {
        lblAvisoPrimeiroNome.setVisible(false);
        lblAvisoSegundo.setVisible(false);
        lblAvisoCodigo.setVisible(false);
        lblAvisoData.setVisible(false);
        lblAvisoEmail.setVisible(false);
        lblAvisoTelefone.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGravarEndereco;
    private javax.swing.JButton btnGravarPessoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<ComboItens> cbCidade;
    private javax.swing.JComboBox<ComboItens> cbEstado;
    private javax.swing.JComboBox<String> cbFiltro;
    private javax.swing.JComboBox<ComboItens> cbPais;
    private javax.swing.JFormattedTextField ftfCep;
    private javax.swing.JFormattedTextField ftfCodigo;
    private javax.swing.JFormattedTextField ftfData;
    private javax.swing.JFormattedTextField ftfTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel lblAvisoBairro;
    private javax.swing.JLabel lblAvisoCep;
    private javax.swing.JLabel lblAvisoCodigo;
    private javax.swing.JLabel lblAvisoData;
    private javax.swing.JLabel lblAvisoEmail;
    private javax.swing.JLabel lblAvisoLogradouro;
    private javax.swing.JLabel lblAvisoPrimeiroNome;
    private javax.swing.JLabel lblAvisoSegundo;
    private javax.swing.JLabel lblAvisoTelefone;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblPrimeiroNome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JRadioButton radFisica;
    private javax.swing.JRadioButton radJuridica;
    private javax.swing.JRadioButton radPfisicaC;
    private javax.swing.JRadioButton radPjuridicaC;
    private javax.swing.JTable tblPessoa;
    private javax.swing.JTextField tfdBairro;
    private javax.swing.JTextField tfdComplemento;
    private javax.swing.JTextField tfdConsulta;
    private javax.swing.JTextField tfdEmail;
    private javax.swing.JTextField tfdLogradouro;
    private javax.swing.JTextField tfdNumero;
    private javax.swing.JTextField tfdPrimeiroNome;
    private javax.swing.JTextField tfdSegundo;
    // End of variables declaration//GEN-END:variables
}
